### ISSUE TITLE
Issue with submission stats in User method

### ISSUE THREAD

**Issue by Prathamesh010** [siesgstarena/arena-issue-tracking#25] opened 2020-06-02 15:54 UTC
Some users submission stats is returning null instead of true values

**Comment by Swap76** [comment] 2020-06-02 15:57
@PRATHAMESHGAWAS Thanks for creating the issues. Our team has started working on the bug fix. We will let you know here only when we push the update :-)

**Comment by Swap76** [comment] 2020-06-02 17:35
@PRATHAMESHGAWAS The issue is Fixed now you check now :-)

**Closed as completed** 2020-06-02 17:42 UTC
Labels: bug
